---
k3s_kubeconfig_remote_path: /etc/rancher/k3s/k3s.yaml
k3s_kubeconfig_local_path: "{{ playbook_dir }}/../../kubeconfig"
k3s_kubeconfig_server_url: "https://{{ k3s_node_ip | default(ansible_host) }}:6443"
